# Generated by Django 4.0.2 on 2022-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0002_alter_plan_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
