# Generated by Django 3.2.9 on 2022-03-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyExpenses', '0005_auto_20220227_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='login',
        ),
        migrations.RemoveField(
            model_name='child',
            name='password',
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
    ]
