# Generated by Django 3.2.9 on 2022-03-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0007_alter_child_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
        migrations.AddField(
            model_name='child',
            name='login',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='child',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dailyExpenses.parent'),
        ),
    ]
