# Generated by Django 3.2.9 on 2022-03-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0010_auto_20220307_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyExpenses.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyExpenses.parent')),
            ],
            options={
                'unique_together': {('child', 'parent')},
            },
        ),
    ]
