# Generated by Django 3.2.9 on 2022-03-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0011_auto_20220325_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_invitations', to='dailyExpenses.child'),
        ),
    ]
