# Generated by Django 3.2.9 on 2022-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0012_auto_20220328_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
