# Generated by Django 3.2.9 on 2022-04-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0015_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='confirm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
