# Generated by Django 3.2.9 on 2022-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyExpenses', '0016_alter_plan_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
